train:
  - class_name: albumentations.Flip
    params:
      p: 0.5
  - class_name: albumentations.ShiftScaleRotate
    params:
      shift_limit: 0.0625
      scale_limit: 0.1
      rotate_limit: 10
  - class_name: albumentations.Normalize
    params:
      mean: ${datamodule.dataset.mean}
      std: ${datamodule.dataset.std}
      p: 1.0
  - class_name: albumentations.pytorch.transforms.ToTensorV2
    params:
      p: 1.0
val:
  - class_name: albumentations.Normalize
    params:
      mean: ${datamodule.dataset.mean}
      std: ${datamodule.dataset.std}
      p: 1.0
  - class_name: albumentations.pytorch.transforms.ToTensorV2
    params:
      p: 1.0
