class_name: models.nets.lenet.LeNetV6
input_size: 32 
stem:
  class_name: models.stems.patch.PatchStem
  params:
    patch_size: 4
    use_conv: true
neck:
  class_name: models.necks.patch.PatchNorm
head:
  class_name: models.heads.fc.FullyConnectedHead
  params:
    layer_units: 
      - ${datamodule.dataset.n_classes}
    activations: ["id"]
    dropout_rates: [0.0]
