class_name: models.nets.base.ClfModel
ip: {c: 3, h: 32, w: 32}
layers:
  s1: [ip, 1, ResNetBlock, [3, 64, {s: 1}]] # [n, 32, 32, 32]
  t1: [s1, 1, ResNetBlock, [64, 64]] # [n, 32, 32, 32] 

  t2: [t1, 1, LightResNetBlock, [64, 128, {s: 2}]] # [n, 64, 16, 16] 
  t3: [t2, 2, LightResNetBlock, [128, 128]] # [n, 64, 16, 16] 

  t4: [t3, 1, LightResNetBlock, [128, 256, {s: 2}]] # [n, 128, 8, 8] 
  t5: [t4, 2, LightResNetBlock, [256, 256]] # [n, 128, 8, 8] 

  n1: [t5, 1, AvgPool, [256, {flatten: false}]] # [n, 256]
  h1: [n1, 1, ConvHead, [256, ["${datamodule.dataset.n_classes}"]]] # [n, 10]
