class_name: models.nets.base.ClfModel
ip: {c: 3, h: 32, w: 32}
layers:
  s1: [ip, 1, SoftSplit, [3, 64, 4, 2]] # [n, 16*16, 64]
  t1: [s1, 1, T2TBlock, [64, 96, 16, 3, 2]] # [n, 8*8, 96]
  t2: [t1, 2, TransformerEncoder, [96, 2, 2, 0.1]] # [n, 8*8, 86]
  t3: [t2, 1, T2TBlock, [96, 128, 8, 3, 2]] # [n, 4*4, 128]
  t4: [t3, 2, TransformerEncoder, [128, 2, 2, 0.1]] # [n, 4*4, 128]
  n1: [t4, 1, SequencePooling, [128]] # [n, 128]
  h1: [n1, 1, FCHead, [128, ["${datamodule.dataset.n_classes}"]]] # [n, 10]
