class_name: models.nets.vit.ViTTiny
input_size: 32 
stem:
  class_name: models.stems.patch.T2TPatchV2
  params:
    kernel_sizes: [3, 3, 3]
    strides: [1, 1, 2]
    image_h: ${model.input_size}
neck:
  class_name: models.necks.patch.SequencePooling
head:
  class_name: models.heads.fc.FullyConnectedHead
  params:
    layer_units: 
      - ${datamodule.dataset.n_classes}
