lr: 0.000001
max_lr: 0.01 # vit: 0.001 # conv: 0.01
wd: 0.0005 # vit: 0.05, conv: 0.0005
bs: 128
epochs: 60
seed: 666
debug: False
mode: max
monitor: ${metric._primary}
lit_model:
  class_name: lit_models.image_clf.LitImageClassifier
trainer_params:
  devices: 1
  accelerator: gpu
  precision: 16-mixed
  # accumulate_grad_batches: 1
  profiler: False
  max_epochs: ${training.epochs}
  log_every_n_steps: 50
  num_sanity_val_steps: 0
  check_val_every_n_epoch: 1
  default_root_dir: ${general.root_dir}
# resume:
#   checkpoint: epoch=177-valid_accuracy=0.918700.ckpt
