lr: 0.0001
seed: 666
debug: False
n_classes: 10
mode: max
monitor: ${metric._primary}
lit_model:
  class_name: lit_models.image_clf.LitImageClassifier
trainer_params:
  devices: 1
  accelerator: gpu
  precision: 16
  # accumulate_grad_batches: 1
  profiler: False
  max_epochs: 5
  log_every_n_steps: 50
  num_sanity_val_steps: 0
  check_val_every_n_epoch: 1
  default_root_dir: ${general.root_dir}

