path: /home/ajkdrag/workspace/projects/visionlab/data
class_name: datamodules.image_clf_dm.ImageClfDatamodule
dataset:
  class_name: datasets.image_clf_ds.ImageClfDataset
  name: WildAnimals
  mean: [0.229, 0.224, 0.225]
  std: [0.485, 0.456, 0.406]
  n_classes: 10
num_workers: 2
batch_size: 32
test_batch_size:
pin_memory: True
folder_struct: train_val_test
parser_params: {}
