path: /home/ajkdrag/workspace/projects/visionlab/data/fmnist
class_name: datamodules.tv_clf_dm.TorchvisionClfDatamodule
dataset:
  class_name: datasets.tv_clf_ds.TorchvisionClfDataset
  name: FashionMNIST
  mean: [0.1307, 0.1307, 0.1307]
  std: [0.3081, 0.3081, 0.3081]
  n_classes: 10
num_workers: 2
batch_size: 32
test_batch_size: 32
pin_memory: True
splits: [0.7, 0.3]
